name: UnitTests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run Unit tests
    runs-on: ubuntu-latest
   
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image 
      run: docker build -t test_env -f ./__tests__/environment/ .
       
    - name: Run tests inside the container
      run: docker run test_env
