name: UnitTests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
   
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Python Custom Docker image
      run: docker build -t python3 -f ${{ github.workspace }}/dockerfiles/python3.Dockerfile .
    
    - name: Run unit tests
      run: jest

    # - name: Build Custom Docker image
    #   run: docker build -t test_env .
       
    # - name: Run unit tests inside the custom docker container
    #   run: docker run -dit -v "/var/run/docker.sock:/var/run/docker.sock:rw" test_env
    #   # run: docker run test_env
