name: UnitTests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
   
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Custom Docker image
      run: docker build -t test_env .
       
    - name: Run unit tests inside the custom docker container
      run: docker run test_env
